
# This is augmented with dependent services by
# sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    image: cyberdojo/nginx-shas-stub
    build:
      context: source/nginx_stub
    depends_on:
      - client
    init: true
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  client:
    image: cyberdojo/${CYBER_DOJO_SERVER_NAME}-client
    user: ${CYBER_DOJO_CLIENT_USER}
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CLIENT_PORT ]
      context: source/client
    depends_on:
      - ${CYBER_DOJO_SERVER_NAME}
      - selenium
    ports: [ "${CYBER_DOJO_CLIENT_PORT}:${CYBER_DOJO_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  shas:
    image: ${CYBER_DOJO_SHAS_IMAGE}
    user: ${CYBER_DOJO_SERVER_USER}
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_SHAS_PORT ]
      context: source/server
    depends_on:
      - selenium
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]
