
# This is augmented with dependent services by
# sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    image: cyberdojo/nginx-shas-stub
    build:
      context: source/nginx_stub
    init: true
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  client:
    image: ${CYBER_DOJO_SHAS_CLIENT_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    user: ${CYBER_DOJO_SHAS_CLIENT_USER}
    container_name: ${CYBER_DOJO_SHAS_CLIENT_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_SHAS_CLIENT_PORT}:${CYBER_DOJO_SHAS_CLIENT_PORT}" ]
    build:
      args: [ COMMIT_SHA ]
      context: source/client
    env_file:
      - .env
    depends_on:
      - nginx
      - shas
      - selenium
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  shas:
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
    user: ${CYBER_DOJO_SHAS_SERVER_USER}
    container_name: ${CYBER_DOJO_SHAS_SERVER_CONTAINER_NAME}
    ports: [ "${CYBER_DOJO_SHAS_PORT}:${CYBER_DOJO_SHAS_PORT}" ]
    env_file:
      - .env
    build:
      args: [ COMMIT_SHA ]
      context: source/server
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes: [ "./test:/test/:ro" ]
